name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Actualizamos a v4.1.7+ o la más reciente disponible que ya apunta a Node 24
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar dependencias del sistema
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade buildozer cython virtualenv

      - name: Generar APK con Buildozer
        run: |
          # Importante: Aseguramos que el PATH de pip esté disponible
          export PATH=$PATH:$HOME/.local/bin
          yes | buildozer android debug
        
      - name: Subir APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: MiApp-APK-Resultado
          path: bin/*.apk
          retention-days: 5
